### ISSUE TITLE
Need Lang object in local fallbacks

### ISSUE THREAD

**Issue by AmirKarimi** [mohiva/play-silhouette#295]
We always get language from route (ex. `/en/my/action`) so request2lang is useless for us. Subsequently, we need implicit lang (like implicit request) in local fallbacks.

**Comment by akkie** [comment]
It's intended that the local fallback methods do not have the implicit lang parameter because it is possible to override the `request2lang` method with its own logic and this is what you should do if the lang isn't extracted from Accept-Language header. Is there any reason why you not override the `request2lang` method?

**Comment by AmirKarimi** [comment]
We used implicit lang directly everywhere. Now I changed the approach by putting lang into the wrapped request and extract it in request2lang. this way we don't need direct implicit lang anymore.
