### ISSUE TITLE
Is it possible for JWTAthenticator service init() without writing token to data store

### ISSUE THREAD

**Issue by deepcover96** [mohiva/play-silhouette#332]
I am persisting JWT Authenticators in a database to whitelist them.  When a user signs in, I generate a token for them based on the stored token ID that is associated with their account.  I query the database for the Authenticator and call init(JWTAuthenticator) on the Authentication service.  That generates a token to send back to the user with the same token ID as is stored for this user.  The service also tries to save the Token to the database, however I already have one and the unique token IDs collide.  I added a PostgreSQL rule to do nothing when there is a duplicate ID attempted on an insert.  This solved my problem, but I was wondering if there could be a way to call init() or generate a token without requiring the service to save Authenticator to the the store.

**Comment by akkie** [comment]
You should not use the same ID for every created token. I think this is a security risk because this is the same as never expiring tokens. Instead you should store the associated user ID in the claims of the JWT token and then validate against this user ID.

This are the steps you must perform:
* Create a new authenticator
* Modify the claims -> authenticator.copy(customClaims = Some(...))
* Init the authenticator

In the `find` method of the DAO you can then validate the claim data against your whitelist.

Let me know if it works!

**Comment by deepcover96** [comment]
Thank you for your response.  I will go ahead and store the new token with the associated user id like you recommended, so users will receive a new token upon signing in and the old record will be disposed.  Thank you.
