### ISSUE TITLE
AuthInfoDao[T] add method contract/documentation is confusing

### ISSUE THREAD

**Issue by flojdek** [mohiva/play-silhouette#413]
Hello, I got a bit confused by the contract provided in:

https://github.com/mohiva/play-silhouette/blob/550f25fbae323583d80c4806d0271c1603973544/silhouette/app/com/mohiva/play/silhouette/impl/daos/AuthInfoDAO.scala

for method:

```scala
def add(loginInfo: LoginInfo, authInfo: T): Future[T]
```

Can I assume that whenever this function is called silhouette has already checked that there hasn't been done any association between `loginInfo` and `authInfo` already? One of the example implementations uses a `Map[LoginInfo, PasswordInfo]` for which the behavior is more like an upsert/update-or-insert, i.e., if it doesn't exist add/insert it, if it does just update the `authInfo`. So to sum up, shouldn't the contract of this function say something like 'Add new auth info for the given login info or update the auth info for given login info if login info already exists.'.

Also, is this method needed taking into account we already have `save`.

Thanks,
Tomasz

**Comment by akkie** [comment]
Hi,

> Can I assume that whenever this function is called silhouette has already checked that there hasn't been done any association between loginInfo and authInfo already?

No, because this isn't the responsibility of Silhouette. The `add` method is like an insert. It adds a new entry and it's up to the implementer to decide what should happen if an entry already exists. Currently this method is not used in the core of Silhouette. It's [used](https://github.com/mohiva/play-silhouette-seed/blob/master/app/controllers/SignUpController.scala#L67) in the seed templates to add the new auth info on registration. This is a save(in the meaning of secure) operation because the code checks previously that the `LoginInfo` created on registration doesn't exists. And if the `LoginInfo` doesn't exists there can not be an associated `AuthInfo`.

The [update](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L72) and the [find](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L68) methods are the only both methods used in the core. In this case it's guaranteed that no error can occur because it's previously checked if the entry exists before it gets updated.

The `save` method is used like an upsert. This should be used in cases where it's not know or if it's regardless of whether an auth info already exists. The social authentication is an example for such a case because it adds new auth info on the first login and it updates the auth info on every subsequent login.

> One of the example implementations uses a Map[LoginInfo, PasswordInfo] for which the behavior is more like an upsert/update-or-insert, 

This is only a placeholder implementation to get a running application in development or example mode. You should not consider it as a real example.

Does this clarify your question?

**Comment by flojdek** [comment]
Ok. So as I see it, `add` seems to be also a kind of performance optimization in the case the client of this API for sure knows there's no association yet, then he can safely call `add` which makes sense. I was a bit confused how to implement it.

What you wrote makes sense in general. I don't like the naming convention, because `save` is not much different than `add`, but as long as the documentation explains it, and it is doing it properly, it's fine.

Thanks for your explanation. This can be closed now if you think there's nothing to be improved.

**Comment by akkie** [comment]
In a previous version we had only a save method which was then changed because of the reasons mentioned in [this issue](https://github.com/mohiva/play-silhouette/issues/326). It contains also the explanation for the naming scheme if you're interested.

**Comment by flojdek** [comment]
Hehe, it only shows that you can't make everyone happy! :) Anyway, thanks Christian.
