### ISSUE TITLE
Cache Authenticator in serialised version?

### ISSUE THREAD

**Issue by chrissom** [mohiva/play-silhouette#442]
Hi,

I'm coding a webapp with an Angularjs frontend with the [Satellizer](https://github.com/sahat/satellizer) library. 

When I authenticate a user with OAuth2 provider, Silhouette gives me a JWT token and he's cached in server side (Redis) and stored in the front side by Satellizer (LocalStorage). All is good.

I tried to read the cache with a Redis client and it's impossible to make a link between the JWT token from the LocalStorage and Redis.

My question: Why the authenticator is cached like an serialized Scala Object in Redis? It could be more confortable to keep it in the cache as a JWT Token or a JSON? To invalidate a specific token it could be more easy.

**Comment by akkie** [comment]
Hi,

this isn't really a Silhouette issue because your cache solution stores the token in a serialized format. If you like to store it in another way then you can implement your own storage solution based on the `AuthenticatorDAO` in version 3 or based on the `AuthenticatorRepository` in the development version.

Best regards,
Christian
