### ISSUE TITLE
New Feature suggestion - Throttle login attempts

### ISSUE THREAD

**Issue by mslinn** [mohiva/play-silhouette#489]
_PART VI: Much More - Or: Preventing Rapid-Fire Login Attempts_ of [The definitive guide to form-based website authentication](http://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication) has a nice explanation of why it is important to throttle login attempts. Throttling would be a good feature to apply to all Silhouette providers, not just to userid/password logins.

Currently Silhouette provides no mechanism to limit the number or rate of login attempts, so security is very weak.

See also feature suggestion [Show and enforce password strength #87](https://github.com/mohiva/play-silhouette-seed/issues/87)

**Comment by akkie** [comment]
How would you implement such a feature?

I think we could use action composition paired with a fingerprint. We need an additional persistence layer which is bad in my opinion because then we must dictate the structure of the data which prevents the extensibility of the component. We need also something that cleans the data in the backing store.

In my opinion such a future pertains into the seed template because then it's completely customizable to the end user. And this totally reflects the philosophy of Silhouette. I think we had the discussion about the philosophy a while back as you have missed the implementation of the password reset functionality and the other parts which I've recently implemented into the Seed template.

**Comment by mslinn** [comment]
This feature only needs a few configurable parameters and does not need to be otherwise customizable. I would put this feature in the base product so it was available for all types of providers.

I would not use persistent store, just an in-memory [concurrent weak hashmap with timeout](http://stackoverflow.com/questions/3802370/java-time-based-map-cache-with-expiring-keys).

Generating a fingerprint sounds complex. A simple Map[UserId, Seq[DateTime]] would associate the last N unsuccessful login times for any given user id. Successful login would clear the user's map entry. To discourage automated login bots, after N failed attempts each successive login response would be slower slower. To do that, either a Promise could be used to delay a response, or an actor-based implementation could be used.

The only configurable parameters would be:

1. Number of failed login attempts before slowing the response
1. List of # of seconds for each successive response
1. Switch to control if an email should be sent to the user indicating they (or someone/something else) is trying unsuccessfully to login. Email would be sent as soon as the number of failed attempts in (1) is reached.
1. Ditto for a switch to control sending email to the site admin
1. Email address of site admin
1. The weak hashmap TTL would be computed by adding up all the times above, plus an additional parameter value, defaulting to one hour

**Comment by akkie** [comment]
> I would put this feature in the base product so it was available for all types of providers.

With an action that can be composed with other actions?

> I would not use persistent store, just an in-memory concurrent weak hashmap with timeout. This means that thresholds are effectively higher if multiple webapp servers are used.

This could also slow down the complete application if multiple login attempts fail, because it would consume a lot of memory. Maybe we could use the cache interface to handle this, so in production a user could use a distributed cache. We should also think about load balancers.

> Generating a fingerprint sounds complex. A simple Map[UserId, Seq[DateTime]] would associate the last N unsuccessful login times for any given user id.

We only have the user ID after a successful login attempt. So a fingerprint is the only chance to identify a user if he/she is not logged in.

> A switch to control if an email should be sent to the user indicating they (or someone/something else) is trying unsuccessfully to login. Email would be sent as soon as the number of failed attempts in (1) is reached.

I would not send an email directly from core, because then Silhouette must depend on an additional email module. We need also adaptable and translatable templates. Instead I would send an event which can be caught in the application and then the application should handle the further things.

**Comment by mslinn** [comment]
Not sure if action composition or a filter might be better.

Every time a user attempts to log in with username/password we have their desired username. I had assumed that the user would always provide a userid when attempting to log in. When is this untrue? Remember, we do not need to resolve to a valid internal user id, we just need to detect login attempts.

I think the memory requirements are modest in modern terms. For example, if each user averages 3 attempts before logging in, and there are 6,000 simultaneous logged in users with an average of 20 minutes per user, that means a user logs in every 2 seconds on average, there are 6 attempts per second and 18,000 people try to log in every hour. 

Let's say 95% of them succeed within 3 attempts, and they try every 30 seconds until they log in. That means we store on average 2 attempts for 90 seconds for most users. At any given time we expect to only need to store 90 seconds worth of logins for the same 95% of users. This means 2 * 90=180 users. 

Now the other 5% are worst case: let's allow 1 hour before flushing them. 5% of 18,000 is 800 users.

Thus the average storage required needs to support 980 user logins in process. Let's call that 1000 user logins, with an average of 3 attempts. The hashmap needs to store the userid (which will be a 4 byte reference) and 3 Long timestamps (also 4 bytes each). Total is 16 bytes per user * 1000 users = 16K bytes.

Quite modest, I think. Even if I am off by two orders of magnitude, this feature only requires a very modest amount of memory.

+1 on the event. It would be nice to provide a handler that the integrator can wire up easily.

**Comment by akkie** [comment]
I'm not sure if it's a good idea to only throttle the attempts for valid users because this allows an attacker to leak usernames or email addresses. Consider the following scenario. An attacker could run a list of email addresses or usernames against the application. If he know that for correct email addresses or usernames the application throttles the login after 3 attempts, then the attacker knows which email addresses or usernames are available for login.

**Comment by mslinn** [comment]
The SO article I linked to discusses that. At first the interval between attempts becomes several minutes, then longer. This would require many years to crack the login, which is effectively secure. Absolute security is impossible, however this attack vector could be made infeasible by slowing down an attack to the point where it no longer is able to crack a user's password before that user dies of old age.

**Comment by icl7126** [comment]
I agree this would be nice to have out of the box.  

Regarding the implementation, I believe usually it's the IP address what is used to identify an attacker. This way someone else cannot block regular user from login in (but marking account with flag - possible under attack sounds also good).  

I think memory footprint would be small even if it stay completely in memory (several megabytes for 1 000 000 users), I would be more concerned with the performance.

**Comment by esfand-r** [comment]
I actually have a requirement at hand for this.  I’m developing a little library on top of silhouette make it more opinionated for my context. We are going to deploy the eventual app in a clustered environment. We could not get away with a concurrent weak hashmap and without something like memcached, hazelcast or some other distributed key value store where we can do atomic increment.  

Still, and despite using a distributed cache, there are concerns for us if we are bind to a specific implementation. For example my requirement is that the client is only allowed 10 attempts per minute. But at the same time, we don’t want the user to try 10 times in the last second of the minute and then make another 10 calls right away. As a side note, our client is an application, so we don’t want to delay the response, we would like to fail when we are passed a threshold and blacklist IPs after some threshold is passed. At the same time that we limit the rate, we don’t want attackers to be able to block a valid user too, which makes things more complicated.   

I'm not very sure if silhouette is the right place for this. We finally considered it a higher level concern and ended up using memcached this https://github.com/esfand-r/ratelimiter (changed to redis later!!!) using an algorithm that fits my purpose. It was going to be used at the api level. Since every API needs some some of rate limitation anyway, that sounds like good place for it. At the end, and after we decided to go with a proper gateway, this concerns is entirely going to be addressed there (We are going to use https://getkong.org/ most likely) .   This could be a nice optional feature in absence of a gateway or proper rate limiter, but unless folks have a way to plugin their own algorithm, configure rates, windows size and everything else, and use the persistence of their choice (issue as @akkie points out, Silhouette will end up "dictating the structure of the data"), it might not be a very useful feature imho.

**Comment by jmcardon** [comment]
@esfand-r funny enough, I came to say something similar. I'm in a situation where I need to implement throttling.

@akkie, how about making this feature optional? How about some sort of optional opt-in cache service implementation that login events are handled in a non blocking way? It could be an extension (at first, for users using an instance of `CredentialsProvider`) where people using an authentication provider could, in the case of opt-in, have their authentication attempt first validated by the cache (asynchronously), then passed the result to either the credentialsProvider validation, or in the case of a throttle, to a raised exception?

I'd be happy to work on such a feature if you gave me the Ok in regards to my idea.

**Comment by akkie** [comment]
In my opinion it makes sense to provide a plugable mechanism, which lets a user plug in a custom implementation. Something like a trait for which a user can implement a plugin. I'm not sure if it makes really sense to provide a complete implementation in core, because of the different needs such a feature can have. 

If we decide to provide such a plugabe mechanism, then we should decide at which point, it makes most sense, to let the user plug in a rate limit plugin. Does it only makes sense for credentials based providers or does it also make sense for social providers? We should also decide which form such a trait can have and how it should generally work.

So the question is: Do we provide such a plugable mechanism or does anyone have a better idea? And how could such a mechanism be implemented. I'm open for proposals.

**Comment by jmcardon** [comment]
@akkie: I was thinking about it and the social based providers even necessary to throttle? 

I mean, if you're signed up with a social provider, but still need to use the email and password to log in, it's essentially the same as the credentials provider post signup, so the implementation would be ok. If you're using a credentials provider to log in, most of the time, it's via OAuth which calls a popup, and the validation is done on the social provider side, thus no throttling is needed: Social providers will do that for you.

imo, credentials providers is who need it the most, as this is what we have full control over programatically.

My initial opt-in idea would be a trait, another class that extends `PasswordProvider` like Credentials provider where the validation takes place. I.e, an implementation of `def authenticate(credentials: Credentials)` that checks against the key:value login via another class that extends a trait (So the user can provide their own implementation), similar to what you did with `IdentityService[T]`.

This key/value pair wouldn't just be an username:login_attempts structure, but customizable by the user, and would return an `Either[Left, Right]` where right is authenticated and left is not, that could do all sorts of checks, like incremental time-based throttling or whatever the user wants. I Don't think it's necessary to provide the entire implementation, just a framework for which to plug it in. A default implementation would just be nice. I do not think Credentialsprovider itself needs to be changed for this to be default behavior, but it could be something like `ThrottlingCredentialsProvider` or whatever better class name anyone could come up with.

To work around the need for the check for throttles after a login attempt, an addition to eventbus() where we could publish `LoginUnsuccessful` and `LogginSuccessful` events could be used, or you could just subscribe an actor to the existing `LoginEvent` as well with different logic. It depends how verbose you want to be.

I've been thinking about this because I have to provide an implementation for this regardless by the time deployment rolls around for work.

**Comment by esfand-r** [comment]
Could something like ThrottlingAction with a Default naive implementation fit? In my case, If I could do something like ```silhouette.ThrottlingUserAwareAction(trottleOnlyOnFailure = true)```, wire in my own implementation of rate limiter and have ability to do something custom on threshold violated (log, lock, blacklist, notify etc), I think I would have more or less all my use cases covered. 

Sorry I'm not much of an expert in Play but maybe something around

```scala
class Throttler @Inject()(val rateLimiter: RateLimiter) {
  object ThrottledAction extends ActionBuilder[Request] {
    def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]) = {
      rateLimiter.canIncrement(...)
        ...
      block(request)
    }
  }
}

class AController @Inject() (val silhouette: Silhouette[DefaultEnv]) extends Controller (
  def loggedInUser = silhouette.ThrottledAction { implicit request =>
    Ok("!")
  }
}

```

**Comment by esfand-r** [comment]
Could something like ThrottlingAction with a Default naive implementation fit? In my case, If I could do something like ```silhouette.ThrottlingUserAwareAction(trottleOnlyOnFailure = true)```, wire in my own implementation of rate limiter and have ability to do something custom on threshold violated (log, lock, blacklist, notify etc), I think I would have more or less all my use cases covered. 

Sorry I'm not much of an expert in Play but maybe something around

```scala
class Throttler @Inject()(val rateLimiter: RateLimiter) {
  object ThrottledAction extends ActionBuilder[Request] {
    def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]) = {
      rateLimiter.canIncrement(...)
        ...
      block(request)
    }
  }
}

class AController @Inject() (val silhouette: Silhouette[DefaultEnv]) extends Controller (
  def action = silhouette.ThrottledAction { implicit request =>
    Ok("!")
  }
}

```

**Comment by jmcardon** [comment]
That's also another option, but that's rate limiting vs login throttling which can be similar but are not necessarily the same.

I.e throttling based on IP  vs throttling based on username. they both have drawbacks/benefits imo. I.e based on username locks for sure every n attempts for a user, but then an attacker can just keep prodding usernames and cause a DOS.

Based on ip, it doesn't stop an attacker from prodding with multiple IPs. 

In which case,  the best solution would be both throttles per Ip and per user, which is worth it imo if the only overhead incurred is during login.

This is a cool idea

**Comment by esfand-r** [comment]
You are right. Not exactly the same but quite similar. Rate limiter should be able to use a constant or combination of them to throttle depending on the threat model. Username alone is quite vulnerable. Apereo for example provides throttling based on IP or UserName + IP, and allows for implementation of alternative strategies : https://apereo.github.io/cas/5.0.x/installation/Configuring-Authentication-Throttling.html . Requirements could vary quite a bit let's say when we throttle for an auction system vs throttling an admin login for a web application who has straight-forward ways and time to do the recovery.

**Comment by akkie** [comment]
@jmcardon @esfand-r Would it be possible that both of you could work on an example implementation?

**Comment by jmcardon** [comment]
Sure! I'd be glad to give it a shot. @esfand-r if you'd like, we can collaborate.

**Comment by esfand-r** [comment]
Sure @akkie , that sounds fun.  

@jmcardon definitely. Have you already started something? Feel free to ping me if you already have a branch and I could collaborate there. I'm a little jammed for the next 2 weeks to finish up a contract but ill find time. It will be a lot easier for me early April.

**Comment by jmcardon** [comment]
@esfand-r LOL Im in the same situation. Atm, I have a contract to finish by end of april, but I could get something started within the next week (by `something` I mean simply a few ideas for the login throttler but nothing too big, we can refine it as we go)

**Comment by esfand-r** [comment]
:) 👍 I might be able to get to it next week too and will ping you as soon I manage to prepare something. Cheers

**Comment by sief** [comment]
@akkie thanks for reaching out on gitter.

I gave it a quick try with https://github.com/sief/play-guard and the seed app https://github.com/mohiva/play-silhouette-seed. It's pretty straight forward:

In `SignInController` I changed the `submit` method:
```
// allow 2 failures immediately and get a new token every 10 seconds
private val httpErrorRateLimited = HttpErrorRateLimitAction(new RateLimiter(2, 1f / 10, "test failure rate limit")) { _ => BadRequest("failure rate exceeded") }

def submit = (httpErrorRateLimited andThen silhouette.UnsecuredAction).async { implicit request =>
```
and
```
 }.recover {
  case e: ProviderException =>
    Unauthorized(views.html.signIn(SignInForm.form.withError("password", Messages("invalid.credentials")), socialProviderRegistry))
}
```
If you want to keep the Redirect in case of wrong credentials you could use `FailureRateLimitFunction` directly an check for anything in the `ResponseHeader`.

**Comment by akkie** [comment]
@sief Great, thanks for testing this out! @esfand-r @jmcardon would the `play-guard` module be an option instead of implementing such functionality directly into Silhouette? @sief Are you open for pull requests, regarding functionality we have talked here and which isn't implemented in your module?

As mentioned previously in this issue and also in [gitter](https://gitter.im/mohiva/play-silhouette?at=58e27d16408f90be66846cea), for me it makes most sense to implement such functionality in a third-party module and I think the `play-guard` module looks really promising.

If we can agree, then I would create a new documentation point called "Rate limiting". Maybe @sief could write a small tutorial how the both libraries can be used together? Generally, any help or ideas are highly appreciated!

**Comment by esfand-r** [comment]
@akkie I think it's a great option. I tried a few different ways directly into Silhouette but it never looked clean enough and I think it's mainly because this is not really a concern Silhouette should be addressing directly. Something separate from Silhouette is a far better option imho too. The way @sief combines ratelimiter with a silhouette action is quit neat. Some of the required functionality mentioned here are more meaningful as issues or pull requests on a library such as play-gaurd instead of play-silhouette. Cheers

**Comment by sief** [comment]
@akkie Sure, PRs are always welcome. Can someone write a brief summary of which additional features you need? 

BTW: I've already been thinking about a pluggable persistence mechanism for the buckets.

**Comment by jmcardon** [comment]
@sief login throttling actions per IP as well as per user. Can play guard throttle based on an identity? It seems ip based from what I saw.

**Comment by sief** [comment]
@jmcardon with the `FailureRateLimitFunction` you can throttle failures based on anything you can retrieve from the request, even if it's an attribute of a WrappedRequest. 
`HttpErrorRateLimitAction` ist just for convenience if you want to throttle based on  IP and HTTP result code.

**Comment by akkie** [comment]
@esfand-r @jmcardon @sief It would be nice if we could find a conclusion about the route we should take and maybe to define the next parts we should do to resolve this issue.

From my standpoint the issue could be closed because such future doesn't pertain to the core of Silhouette. With [play-guard](https://github.com/sief/play-guard) there exists a lib which provides rate-limiting functionality that can be used with Silhouette. So in my opinion there are two things we can do from our side:

* Create a new "Additional modules" page in the doc and link to the `play-guard` module with a short description of the module.
* Create a new "Rate limiting" page in the docs and provide examples how both modules can be used together.

The first proposal is easy and no additional help is needed. The second proposal needs help, because someone must write and test some examples. My priorities are currently focused on the next release and  the framework agnostic version of Silhouette. So I need here help from you. So is anyone willing to invest some time based on the chosen proposal?

**Comment by jmcardon** [comment]
@akkie I'd be willing to. Im freed up friday to work on this.

I'd be leaning more towards option #2, or even a small module (like silhouette persistence) with a custom action that just works out of the box

**Comment by esfand-r** [comment]
@akkie I think it makes sense that this issue is closed too. imho a new page in the doc for rate-limiting and a link to play-guard as an alternative with link to a sample on Github which uses the 2 together would be great. It might be preferable to avoid giving examples directly on the doc as they might introduce unnecessary maintenance.  Rate-limiting page could gradually improve and include links to other libraries when something new comes along and maybe even contain information/links to rate-limiting using gateways which is a nice alternative depending on the project we are dealing with, scale, budget etc.

**Comment by sief** [comment]
@akkie I'll be extremely busy for the next weeks, but I should be able to answer questions or write some code examples or custom ActionFunctions.

**Comment by akkie** [comment]
@jmcardon :+1: for your help. I'm not sure if a single custom action would be enough because Silhouette has three actions which could be protected by rate limiting. In my opinion action composition is the way to go.

@esfand-r :+1: I absolutely agree. I had the same thoughts about that. It's my plan to create a new repository for code examples for common use-cases and frequently asked questions. This would be the right place for the rate limiting examples too.

@sief Would be great if you could help here :+1:

**Comment by jmcardon** [comment]
@akkie almost through exams! 1 more to go. 

Okay I'll do my best for an implementation that can be extended by the user's custom logic, as well as maybe a default impl? If it's unsatisfactory we can just keep the examples, It would just probably save a lot of people boilerplate if they simply used a silhouette-packaged impl that works with `Env#I`,

As far as examples though, while they do increase maintenance, I don't mind contributing to that end. Definitely examples help. I.e, I ran into as situation where I needed to secure a websocket, but actually,

**Comment by akkie** [comment]
@jmcardon I'm not sure if it's worth trying. In my opinion it doesn't make sense to build wrappers around the `play-guard` module, because that would increase maintenance on our side. Let us first try to write some examples for the common rate-limiting use cases with Silhouette and play-guard. If we see that the user must write a lot of boilerplate then we can consider how we can avoid that.

> I.e, I ran into as situation where I needed to secure a websocket, but realized most native browser impls don't let you set custom headers unless you replace the entire http layer with something like socket.io, but do transmit cookies, so moving the token temporarily to a cookie then extracting the token from the cookie into an implicit request worked. Made me think there could be some sort of cookie authentication done for websockets specifically given setting custom headers on websockets is not usually supported in most libraries. (Totally sidetracked here)

You can transport the token in the query string and Silhouette supports this already.

**Comment by jmcardon** [comment]
I was trying to avoid the query string method for the sake of not having tokens end up in logs.

**Comment by akkie** [comment]
Any news here?

**Comment by jmcardon** [comment]
Hi @akkie 

I tried play-guard now that I finally got some time, and implemented both @sief 's example, as well as a custom one using a `SecuredRequest` specific to silhouette. You can see this at: https://github.com/jmcardon/play-silhouette-seed, particularly in the `UserLimiter` object implemented on `ApplicationController`, `SignInController` and the test cases. This fork of your project was slightly modified for testing (I removed the csrf token on the signin page because it was giving me errors when I tried to submit a bogus sign in), but I added two more test cases for actions that should be throttled, both of which are passing.

I also wrote some documentation on readme.io, but because I lack an open source license, I can't add any new pages for public viewing just for testing, and I tried but I couldn't find any way to add new pages in "suggest edits", so I went ahead and made some sample new docs viewable [here](http://imgur.com/a/hxRC9).

Let me know what you think. I may just be dumb but I couldn't find a way to open a new docs page.

**Comment by akkie** [comment]
@jmcardon I've created the "rate limiting" page in the doc. Now you can suggest the edits. The sample looks good to me :+1:

**Comment by jmcardon** [comment]
Submitted!

If all is well, the issue can be closed now.

**Comment by akkie** [comment]
Great! I've merged the suggested edits. The page is now available at: https://www.silhouette.rocks/docs/rate-limiting


Thanks to all!
