### ISSUE TITLE
New Feature: silhouette.securedAction to have the option to take both a custom Authorization object as well as an Error handler?

### ISSUE THREAD

**Issue by jmcardon** [mohiva/play-silhouette#498]
I'll start of by saying hi Silhouette community. I absolutely love the library!

As a feature, I was thinking whether it would be possible to implement two parameters of custom logic within SecuredAction, as this avoids a lot of boilerplate code. Imagine a situation where you have the same authentication scheme (i.e JWT) but users with escalated priviledges.

As it stands, it's possible to override the entire local global error handler via DI, but that's not the point, because this custom logic would only apply to certain routes. You can define an authorization object, but correct me if I'm wrong, but you can't pass both an Authorization and a SecuredErrorHandler to an action. 

You could, in turn, simply make it a secure action and perform operations on the Identity itself, but this is the bolierplate that I'm talking about, that you could solve with the Authorization object, but now you can't implement custom logic on how the controller handles the onNotAuthrorized event. 

Correct me if I am wrong by all means, but I don't see a way of doing this currently, so it would give way for some pretty cool flexibility within the Authorization logic.

Thanks for your time in reading this!

**Comment by akkie** [comment]
Hi,

thanks for your interest and thanks for taking the time to write this future request. 

This is already possible. If you look at the `apply` methods of the [SecuredActionBuilder](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/actions/SecuredAction.scala#L179) then you can see that this methods return a new `SecuredActionBuilder` constructed with the parameter of the `apply` method. So you can easily chain your call.

```scala
def index = silhouette.SecuredAction(errorHandler)(WithProvider("twitter")) { implicit request =>
  Ok(views.html.index(request.identity))
}
```

The order is indifferent. So you can also write:
```scala
def index = silhouette.SecuredAction(WithProvider("twitter"))(errorHandler) { implicit request =>
  Ok(views.html.index(request.identity))
}
```

As noted in the [ISSUE_TEMPLATE](https://github.com/mohiva/play-silhouette/blob/master/.github/ISSUE_TEMPLATE.md), it is better to discuss future requests in our [forum](http://discourse.silhouette.rocks/) because we try to keep the issue tracker only for real/confirmed issues.
