### ISSUE TITLE
Create a BCryptSHA256PasswordHasher that supports passwords >= 72 characters

### ISSUE THREAD

**Issue by graingert** [mohiva/play-silhouette#504]
### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. sign up with password > 72 characters long
2. attempt sign in with a different password with the same 72 character prefex as original password
3. sign in is not successful

### Actual Behavior

1. sign up with password > 72 characters long
2. attempt sign in with a different password with the same 72 character prefex as original password
3. sign in is successful

See the [django docs](https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#using-bcrypt-with-django) for an example of a different framework with the same issue

I propose the the BCryptPasswordHasher raises an exception when presented with a password > 72 characters long, and BCrypt256PasswordHasher is the new default.

Docs should be updated on how to configure both to roll old passwords to new passwords.

**Comment by akkie** [comment]
Thanks, for the information! After reading a bit about the issue, I think your proposal make sense and it's the preferred way for passwords longer then 72 characters to hash it with sha256 first. I'm not sure if throwing an exception is the best way, because it would only make the application unusable for user with long passwords, but it would not necessarily persuade the developer of the application to change the underlying hasher. To deprecate the old version is also not a good idea, because if a web application do not allow passwords greater than 72 characters the current approach is also reasonable and secure.

So in my opinion, documenting the pitfalls of the `BCryptPasswordHasher` and proposing the new `BCrypt256PasswordHasher` should be enough. What do you think?

**Comment by akkie** [comment]
Some additional links:
http://crypto.stackexchange.com/questions/24993/is-there-a-way-to-use-bcrypt-with-passwords-longer-than-72-bytes-securely
http://security.stackexchange.com/questions/151297/using-sha-256-to-preprocess-password-before-bcrypt
http://crypto.stackexchange.com/questions/32341/long-passwords-and-bcrypt

**Comment by graingert** [comment]
While looking into this I also found out about the PHC (password hashing contest) and the winner Argon2  https://github.com/mohiva/play-silhouette/issues/505

**Comment by graingert** [comment]
@akkie

> So in my opinion, documenting the pitfalls of the BCryptPasswordHasher and proposing the new BCrypt256PasswordHasher should be enough. What do you think?

Sounds great!

**Comment by graingert** [comment]
@akkie any update on this, or are you waiting for me to make a PR?

**Comment by akkie** [comment]
@graingert It was one of the next things on my agenda. But it would great if you could find the time to create a PR. So that I can concentrate on the documentation changes and the seed template.

**Comment by akkie** [comment]
@graingert Do you create a PR?
