### ISSUE TITLE
Exception thrown misleading when OAuth2 provider refuses to return an access token

### ISSUE THREAD

**Issue by epot** [mohiva/play-silhouette#527]
I am currently playing with Silhouette 5.0.0-RC2, and I find the getAccessToken error handling a bit misleading. If the provider answers a BadRequest when an access token is requested, then the exception will say:

    Cannot build OAuth2Info because of invalid response format: List((/access_token,List(JsonValidationError(List(error.path.missing),WrappedArray()))))".

Maybe I am missing something, but in the case the method returns something different than a HTTP OK (200), would it be clearer to put that in the exception message? In my case, I had to debug step-by-step or increase the logging verbosity to see that the provider was actually saying:

    [Silhouette][google] Access token response: [{
      "error" : "redirect_uri_mismatch"
    }]

What do you think?

**Comment by akkie** [comment]
I'm aware of this issue and we do this already for [the case](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala#L250) that the result is not a JSON object.

The other case is a bit trickier, because it could lead to issues where secure credentials could be written to log files. Maybe a provider changes the structure of the successful result, so that it cannot be parsed to a `OAuth2Info` instance. In this case the access token could be printed to a log file which might be bad if an attacker has access to the log files.

**Comment by epot** [comment]
Ok, thanks for the clarification.
But in my current case, where the result is not successful, do you agree that trying to parse the json is not relevant?
I was thinking of something like this:

    protected def buildInfo(response: WSResponse): Try[OAuth2Info] = {
      Try(response.json) match {
        case Success(json) if response.status == 200 => json.validate[OAuth2Info].asEither.fold(
          error => Failure(new UnexpectedResponseException(InvalidInfoFormat.format(id, error))),
          info => Success(info)
        )
        case Failure(error) => Failure(new UnexpectedResponseException(JsonParseError.format(id, response.body, error)))
      }
    }

**Comment by akkie** [comment]
I'm not sure if every provider returns status code 200 for a successful response. It would make sense, but I'm not sure if every provider does this. Maybe we could check for 2xx status codes or better we define a global successful status code and let the concrete provider override the code if another is used.

**Comment by epot** [comment]
Yes, sounds good :)
