### ISSUE TITLE
Use case classes in SilhouetteExceptions to allow pattern matching in user code

### ISSUE THREAD

**Issue by mavarazy** [mohiva/play-silhouette#530]
### Expected Behavior

I would like to translate auth exceptions from internal SilhouetteExceptions to my exception hierarchy, it would be nice to be able to match Exceptions with case class matching

### Actual Behavior

I need to fallback to `isInstanceOf[]`

**Comment by akkie** [comment]
Where is the problem? Could you please provide an example?

**Comment by mavarazy** [comment]
The code, that I have is following
```scala
def login(logIn: LogInRequest): Future[AuthServiceResult] = {
    credentialsProvider.authenticate(logIn.toCredentials()).flatMap { loginInfo =>
      userService.retrieve(loginInfo).flatMap {
        case Some(user) =>
          Future.successful(UserLoggedIn(user, loginInfo))
        case None =>
          checkUserExists(logIn.email).
            map(_ => throw FieldValidationError("email", "Email or Password is wrong"))
      }
    } recoverWith( {
      case t: Throwable if (t.isInstanceOf[InvalidPasswordException]) =>
        Future.failed(FieldValidationError("email", "Email or Password does not match"))
      case t: Throwable if (t.isInstanceOf[IdentityNotFoundException]) =>
        Future.failed(FieldValidationError("email", "This email was not registered"))
    })
  }
```
What I would expect is
```scala
    recoverWith( {
      case _: InvalidPasswordException =>
        Future.failed(FieldValidationError("email", "Email or Password does not match"))
      case _: IdentityNotFoundException =>
        Future.failed(FieldValidationError("email", "This email was not registered"))
    })
```

**Comment by akkie** [comment]
I'm not really sure I understand your issue. Have you tried your suggested example? What's the error you get?

Maybe I miss something, but pattern matching works with any type regardless of whether it's a case class or not. The advantage of a case class is that you can use the extractor the compiler creates automatically for a case class. You could also create an extractor (unapply) method in the companion object of a normal class to get the same behavior. 

The reason why we not use case classes for exceptions, is that case classes cannot extend other case classes. So you cannot create an exception hierarchy like Silhouette provides.

So in my opinion, your suggested example should works as expected. If we would use a case class for our exceptions, then you could use the extractor like:
```scala
recoverWith( {
  case InvalidPasswordException(msg) =>
    Future.failed(FieldValidationError("email", "Email or Password does not match"))
  case IdentityNotFoundException(msg) =>
    Future.failed(FieldValidationError("email", "This email was not registered"))
})
```

Please let me know if I miss something. Otherwise, please close the issue if you do not have any further questions.

**Comment by mavarazy** [comment]
Oh sorry, you are right, this is my mistake.
Thanks for help
