### ISSUE TITLE
Support Play 2.8.0

### ISSUE THREAD

**Issue by nafg** [mohiva/play-silhouette#569]

**Comment by OlivierNouguier** [comment]
It is not working ?

**Comment by akkie** [comment]
Changes should be minor. If I look over the migration guide, I cannot see anything that should be changed in Silhouette instead of the Play and maybe the SBT version.

Silhouette supports already Scala 2.13. So the only thing in this case is to remove the Scala 2.11 version from the SBT config.

A PR would be welcome

**Comment by nafg** [comment]
See #570

**Comment by akkie** [comment]
I've released Silhouette 7.0.0-RC1 which targets Play 2.8.1. Many thanks to @nafg

**Comment by akkie** [comment]
The final 7.0.0 is released

**Comment by rorygraves** [comment]
Great stuff thank @nafg and @akkie
